export default {
    "width": 1008,
    "height": 528,
    "tileWidth": 24,
    "map": [
        "ff   fffffffffffffffffffffffffffffffffffff",
        "ff   fffffffffffffffffffffffffffffffffffff",
        "ff  r                                  dff",
        "ff r                                  d ff",
        "ffr                                  d  ff",
        "fffffffffffffffffffffffffffffffffffff   ff",
        "fffffffffffffffffffffffffffffffffffff   ff",
        "    lffd      lffd      lffd      lff   ff",
        "   l ff d    l ff d    l ff d    l ff   ff",
        "  l  ff  d  l  ff  d  l  ff  d  l  ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff  u  l  ff  u  l  ff  u  l  ff  u  l  ff",
        "ff u    l ff u    l ff u    l ff u    l ff",
        "ffu      lffu      lffu      lffu      lff",
        "ffffffffffffffffffffffffffffffffffffffffff",
        "ffffffffffffffffffffffffffffffffffffffffff",
    ]
}
