export default {
    "width": 1008,
    "height": 528,
    "tileWidth": 24,
    "map": [
        "ff   fffffffffffffffffffffffffffffffffffff",
        "ff   fffffffffffffffffffffffffffffffffffff",
        "ff                                      ff",
        "ff                                      ff",
        "ff                                      ff",
        "fffffffffffffffffffffffffffffffffffff   ff",
        "fffffffffffffffffffffffffffffffffffff   ff",
        "     ff        ff        ff        ff   ff",
        "     ff        ff        ff        ff   ff",
        "     ff        ff        ff        ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff   ff   ff   ff   ff   ff   ff   ff   ff",
        "ff        ff        ff        ff        ff",
        "ff        ff        ff        ff        ff",
        "ff        ff        ff        ff        ff",
        "ffffffffffffffffffffffffffffffffffffffffff",
        "ffffffffffffffffffffffffffffffffffffffffff",
    ]
}
